### ISSUE TITLE
Documentation Template

### ISSUE THREAD

**Issue by JasonBernert** [DavideDaniel/hackoregon-frontend-starter#2]
I've been talking to folks about enforcing and standardizing documentation for Hack Oregon products. I'll be leading a [discussion](https://github.com/JasonBernert/hack-oregon-documentation-notes/blob/master/README.md) next week on the topic.

I'm wondering if there's any value adding a `README-TEMPLATE.md`, or something like it, to starter repos. It would include a few simple prompts that developers would fill out to help develop good documentation practices: describe what you're building, steps to get it running, example implementations, etc. 

We can discuss what the prompts can be, but I thought keeping a template in starter repos would be a nice way to update templates as we see fit.

**Comment by JasonBernert** [comment]
:rage1: WHY U NO COMMENT BACK?!?!?!? :rage4: 



Just joking around. I'm leading the docs discussion right now.

**Comment by DavideDaniel** [comment]
Ha.. yep, I think there's value.. should have a template with some info in the wiki maybe..
